---
name: Max Czapanskiy, PhD
position: "UC Santa Barbara, Assistant Professor of Teaching"
profilepic: flippyhairs.png
email: "maxczap@ucsb.edu"
github: FlukeAndFeather
www: flukeandfeather.com
orcid: 0000-0002-6302-905X
headcolor: 619D8C
date: "`r format(Sys.time(), '%B %Y')`"
output: 
  vitae::awesomecv:
    page_total: true
knit: (function(inputFile, encoding) { rmarkdown::render(inputFile, encoding = encoding, output_file = file.path(dirname(inputFile), sprintf("Czapanskiy_CV_%s", Sys.Date()))) })
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
library(tidyverse)
library(vitae)
source("util.R")
```

# Appointments

```{r work}
tribble(
  ~ what, ~ when, ~ with,
  "Assistant Professor of Teaching",
    "2024 - Present",
    "UC Santa Barbara, Bren School of Environmental Science and Management & College of Creative Studies",
  "Postdoctoral Scholar",
    "2022 - 2024",
    "NOAA, Southwest Fisheries Science Center | UC Santa Cruz, Ocean Sciences"
) %>% 
  detailed_entries(what, when, with)
```

# Education

```{r education}
tribble(
  ~ degree, ~ uni, ~ loc, ~ dates,
  "PhD in Biology", "Stanford University", "Pacific Grove, CA", "2022",
  "MS in Geographic Information Systems", "San Francisco State University", "San Francisco, CA", "2018",
  "BS in Computer Science", "Columbia University", "New York, NY", "2014") %>% 
  detailed_entries(degree, dates, uni, loc)
```

# Teaching

```{r teaching}
tribble(
  ~ year, ~ title, ~ institution,
  "2025",
    "Intro to Marine Data Science",
    "UC Santa Barbara",
  "2024",
    "Statistics for Environmental Data Science",
    "UC Santa Barbara",
  "2023",
    "Data Science for Eco/Evo",
    "UC Santa Cruz",
  "2021", 
    "Just Enough Software Engineering (For Scientists)",
    "Stanford University",
  "2018 - present",
    "Data Carpentry (Certified Instructor)",
    "The Carpentries"
) %>% 
  brief_entries(
    what = title,
    when = year,
    with = institution,
    .protect = FALSE
  )
```

# Publications

```{r publications}
bib2df::bib2df("works.bib") %>% 
  mutate(AUTHOR = map_chr(AUTHOR, combine_authors)) %>% 
  detailed_entries(
    what = AUTHOR,
    when = YEAR, 
    with = TITLE, 
    where = JOURNAL,
    .protect = FALSE
  )
```

